/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './quotes-form-details.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './quotes-form-details.component';
const styles_QuotesFormDetailsComponent:any[] = [i0.styles];
export const RenderType_QuotesFormDetailsComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_QuotesFormDetailsComponent,data:{}});
export function View_QuotesFormDetailsComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_QuotesFormDetailsComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-quotes-form-details',
      ([] as any[]),(null as any),(null as any),(null as any),View_QuotesFormDetailsComponent_0,
      RenderType_QuotesFormDetailsComponent)),i1.ɵdid(1,114688,(null as any),0,i2.QuotesFormDetailsComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const QuotesFormDetailsComponentNgFactory:i1.ComponentFactory<i2.QuotesFormDetailsComponent> = i1.ɵccf('app-quotes-form-details',
    i2.QuotesFormDetailsComponent,View_QuotesFormDetailsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYXJ1bmRhL0Rlc2t0b3AvUHJvamVjdHMvVGhlUXVvdGVzL3NyYy9hcHAvcXVvdGVzLWZvcm0tZGV0YWlscy9xdW90ZXMtZm9ybS1kZXRhaWxzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2FydW5kYS9EZXNrdG9wL1Byb2plY3RzL1RoZVF1b3Rlcy9zcmMvYXBwL3F1b3Rlcy1mb3JtLWRldGFpbHMvcXVvdGVzLWZvcm0tZGV0YWlscy5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL2FydW5kYS9EZXNrdG9wL1Byb2plY3RzL1RoZVF1b3Rlcy9zcmMvYXBwL3F1b3Rlcy1mb3JtLWRldGFpbHMvcXVvdGVzLWZvcm0tZGV0YWlscy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvYXJ1bmRhL0Rlc2t0b3AvUHJvamVjdHMvVGhlUXVvdGVzL3NyYy9hcHAvcXVvdGVzLWZvcm0tZGV0YWlscy9xdW90ZXMtZm9ybS1kZXRhaWxzLmNvbXBvbmVudC50cy5RdW90ZXNGb3JtRGV0YWlsc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuIiwiPGFwcC1xdW90ZXMtZm9ybS1kZXRhaWxzPjwvYXBwLXF1b3Rlcy1mb3JtLWRldGFpbHM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBOzs7b0JDQUE7TUFBQTsyQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
