/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYXJ1bmRhL0Rlc2t0b3AvUHJvamVjdHMvVGhlUXVvdGVzL3NyYy9hcHAvcXVvdGVzLWZvcm0tZGV0YWlscy9xdW90ZXMtZm9ybS1kZXRhaWxzLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hcnVuZGEvRGVza3RvcC9Qcm9qZWN0cy9UaGVRdW90ZXMvc3JjL2FwcC9xdW90ZXMtZm9ybS1kZXRhaWxzL3F1b3Rlcy1mb3JtLWRldGFpbHMuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
