/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#newquote[_ngcontent-%COMP%] {\n  color: grey;\n  padding-left: 40px;\n}\n.form-control[_ngcontent-%COMP%] {\n  color: grey;\n\n}\n.col-md-6[_ngcontent-%COMP%] {\n  font-family: \'Cuprum\', sans-serif;\n  font-size: 20px;\n  padding-left: 2px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYXJ1bmRhL0Rlc2t0b3AvUHJvamVjdHMvVGhlUXVvdGVzL3NyYy9hcHAvcXVvdGVzLWZvcm0vcXVvdGVzLWZvcm0uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2FydW5kYS9EZXNrdG9wL1Byb2plY3RzL1RoZVF1b3Rlcy9zcmMvYXBwL3F1b3Rlcy1mb3JtL3F1b3Rlcy1mb3JtLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
