/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#Title[_ngcontent-%COMP%] {\n  color: orange;\n  font-size: 3em;\n  margin-top: 25px;\n  font-family: \'Gamja Flower\', cursive;\n  text-align: center;\n\n}\n\n#chant[_ngcontent-%COMP%] {\n  color: black;\n  font-family: \'Gamja Flower\', cursive;\n  font-size: 30px;\n  font-weight: lighter;\n  text-align: center;\n  padding-left: 40px;\n  margin-left: 50px;\n}\n\n.btn[_ngcontent-%COMP%]   btn-submit[_ngcontent-%COMP%] {\n  color: blue;\n  margin-left: 50px;\n  float: left;\n}\n\n.row[_ngcontent-%COMP%] {\n  \n  background-color: #bad6dd;\n  margin-left: 70px;\n  margin-right: 70px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYXJ1bmRhL0Rlc2t0b3AvUHJvamVjdHMvVGhlUXVvdGVzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hcnVuZGEvRGVza3RvcC9Qcm9qZWN0cy9UaGVRdW90ZXMvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
