/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './quotes-form/quotes-form.component.ngfactory';
import * as i3 from './quotes-form/quotes-form.component';
import * as i4 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),29,'div',[['class',
      'container-fluid'],['style','background-color: #123456']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['\n  '])),(_l()(),i1.ɵeld(2,0,(null as any),(null as any),26,'div',[['class',
      'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['\n    '])),(_l()(),i1.ɵeld(4,0,(null as any),
          (null as any),0,'div',[['class','col-md-2'],['style','background-color: #123456']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['\n    '])),(_l()(),i1.ɵeld(6,0,(null as any),
          (null as any),19,'div',[['class','col-md-8']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
          ['\n      '])),(_l()(),i1.ɵeld(8,0,(null as any),(null as any),1,'h1',[['id',
          'Title']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['Quotes'])),(_l()(),i1.ɵeld(10,0,(null as any),
          (null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n      '])),
      (_l()(),i1.ɵeld(12,0,(null as any),(null as any),1,'p',[['id','chant']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
          (null as any),['A Chance to Share Your Quotes with the World.'])),(_l()(),
          i1.ɵted(-1,(null as any),['\n      '])),(_l()(),i1.ɵeld(15,0,(null as any),
          (null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n\n'])),
      (_l()(),i1.ɵeld(17,0,(null as any),(null as any),7,'div',[['class','container-fluid']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted(-1,(null as any),['\n  '])),(_l()(),i1.ɵeld(19,0,(null as any),
          (null as any),4,'div',[['class','row']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i1.ɵeld(21,0,(null as any),(null as any),1,'app-quotes-form',([] as any[]),
          (null as any),(null as any),(null as any),i2.View_QuotesFormComponent_0,
          i2.RenderType_QuotesFormComponent)),i1.ɵdid(22,114688,(null as any),0,i3.QuotesFormComponent,
          ([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted(-1,(null as any),
          ['\n  '])),(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵted(-1,
          (null as any),['\n    '])),(_l()(),i1.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i1.ɵeld(27,0,(null as any),(null as any),0,'div',[['class','col-md-2'],
          ['style','background-color:#123456']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n  '])),
      (_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵted(-1,(null as any),['\n']))],
      (_ck,_v) => {
        _ck(_v,22,0);
      },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(1,49152,(null as any),0,i4.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i4.AppComponent> = i1.ɵccf('app-root',
    i4.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYXJ1bmRhL0Rlc2t0b3AvUHJvamVjdHMvVGhlUXVvdGVzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2FydW5kYS9EZXNrdG9wL1Byb2plY3RzL1RoZVF1b3Rlcy9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL2FydW5kYS9EZXNrdG9wL1Byb2plY3RzL1RoZVF1b3Rlcy9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvYXJ1bmRhL0Rlc2t0b3AvUHJvamVjdHMvVGhlUXVvdGVzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyLWZsdWlkXCIgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiAjMTIzNDU2XCI+XG4gIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTJcIiBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6ICMxMjM0NTZcIj48L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLThcIj5cbiAgICAgIDxoMSBpZD1cIlRpdGxlXCI+UXVvdGVzPC9oMT48aHI+XG4gICAgICA8cCBpZD1cImNoYW50XCI+QSBDaGFuY2UgdG8gU2hhcmUgWW91ciBRdW90ZXMgd2l0aCB0aGUgV29ybGQuPC9wPlxuICAgICAgPGhyPlxuXG48ZGl2IGNsYXNzPVwiY29udGFpbmVyLWZsdWlkXCI+XG4gIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICA8YXBwLXF1b3Rlcy1mb3JtPjwvYXBwLXF1b3Rlcy1mb3JtPlxuICA8L2Rpdj5cbjwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtMlwiIHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjojMTIzNDU2XCI+PC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG4iLCI8YXBwLXJvb3Q+PC9hcHAtcm9vdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUEsNENBQStEO01BQUEsV0FDN0Q7TUFBQTtNQUFpQiw4Q0FDZjtVQUFBO1VBQUE7TUFBOEQsOENBQzlEO1VBQUE7VUFBQSw0Q0FBc0I7VUFBQSxlQUNwQjtVQUFBO01BQWUsOENBQVc7VUFBQTtVQUFBLDhCQUFJO01BQzlCO1VBQUEsMERBQWM7VUFBQSxrRUFBaUQ7aUJBQUEsaUNBQy9EO1VBQUE7VUFBQSw4QkFBSTtNQUVWO1VBQUE7TUFBNkIsNENBQzNCO1VBQUE7VUFBQSw4QkFBaUI7TUFDZjtVQUFBOzJDQUFBLFVBQUE7VUFBQSwyQ0FBbUM7VUFBQSxXQUMvQiwwQ0FDRjtVQUFBLDJCQUNJO01BQ047VUFBQTtVQUFBLDhCQUE2RDtNQUN6RCwwQ0FDRjs7UUFORjs7OztvQkNWSjtNQUFBO2FBQUE7VUFBQTs7OyJ9
